### ISSUE TITLE
uninitialized constant JsonHelpers::Launchy

### ISSUE THREAD

**Issue by lewispb** [balvig/utensils#11]
Requiring `require 'utensils/json'` and trying to use `save_and_open_json` errors:

`uninitialized constant JsonHelpers::Launchy`

I guess there's a requirement on using [Launchy](https://github.com/copiousfreetime/launchy), but I don't see that in the gemspec.

**Comment by balvig** [comment]
> I guess there's a requirement on using Launchy, but I don't see that in the gemspec.

I think you nailed it! 🙇
